#-------------------------------------------------------------------------
# Created: Sun Jan 17 00:06:46 2010 by mkntuplecfi.py
#-------------------------------------------------------------------------
import FWCore.ParameterSet.Config as cms
demo =\
cms.EDAnalyzer("Mkntuple",
               ntupleName = cms.untracked.string("ntuple.root"),
               variables  =
               cms.untracked.
               vstring(
    "HcalNoiseSummary                hcalnoise                         1",
    #---------------------------------------------------------------------
    "bool   passHighLevelNoiseFilter()",
    "bool   passLooseNoiseFilter()",
    "bool   passTightNoiseFilter()",
    "float   eventChargeFraction()",
    "float   eventEMEnergy()",
    "float   eventEMFraction()",
    "float   eventHadEnergy()",
    "float   eventTrackEnergy()",
    "float   max10GeVHitTime()",
    "float   max25GeVHitTime()",
    "float   min10GeVHitTime()",
    "float   min25GeVHitTime()",
    "float   minE10TS()",
    "float   minE2Over10TS()",
    "float   minE2TS()",
    "float   minHPDEMF()",
    "float   minRBXEMF()",
    "float   rms10GeVHitTime()",
    "float   rms25GeVHitTime()",
    "int   maxHPDHits()",
    "int   maxRBXHits()",
    "int   maxZeros()",
    "int   noiseFilterStatus()",
    "int   noiseType()",
    "int   num10GeVHits()",
    "int   num25GeVHits()",
    "int   numProblematicRBXs()",
    "/",
    "edmTriggerResults               TriggerResults                    1",
    #---------------------------------------------------------------------
    "bool   accept()",
    "bool   error()",
    "bool   wasrun()",
    "/",
    "recoBeamSpot                    offlineBeamSpot                   1",
    #---------------------------------------------------------------------
    "double   emittanceX()",
    "double   emittanceY()",
    "double   sigmaZ()",
    "double   x0()",
    "double   x0Error()",
    "double   y0()",
    "double   y0Error()",
    "double   z0()",
    "double   z0Error()",
    "/",
    "LumiScalers                     scalersRawToDigi                500",
    #---------------------------------------------------------------------
    "float   instantLumi()",
    "float   instantLumiErr()",
    "unsigned int   bunchNumber()",
    "unsigned int   numOrbits()",
    "/",
    "l1extraL1EmParticle             l1extraParticles_Isolated       500",
    #---------------------------------------------------------------------
    "double   energy()",
    "double   et()",
    "double   eta()",
    "double   phi()",
    "double   pt()",
    "int   charge()",
    "/",
    "l1extraL1EmParticle             l1extraParticles_NonIsolated    500",
    #---------------------------------------------------------------------
    "double   energy()",
    "double   et()",
    "double   eta()",
    "double   phi()",
    "double   pt()",
    "int   charge()",
    "/",
    "recoCaloCluster   hybridSuperClusters_hybridBarrelBasicClusters 500",
    #---------------------------------------------------------------------
    "double   energy()",
    "double   eta()",
    "double   phi()",
    "/",
    "recoCaloJet                     ak5CaloJets                     500",
    #---------------------------------------------------------------------
    "double   energy()",
    "double   et()",
    "double   eta()",
    "double   phi()",
    "float   emEnergyFraction()",
    "float   energyFractionHadronic()",
    "float   towersArea()",
    "/",
    "recoCaloMET                     met                             500",
    #---------------------------------------------------------------------
    "double   et()",
    "double   metSignificance()",
    "double   phi()",
    "/",
    "recoMET                         htMetIC5                        500",
    #---------------------------------------------------------------------
    "double   energy()",
    "double   et()",
    "double   eta()",
    "double   phi()",
    "double   pt()",
    "/",
    "recoMuon                        muons                           500",
    #---------------------------------------------------------------------
    "bool   isCaloMuon()",
    "bool   isGlobalMuon()",
    "bool   isStandAloneMuon()",
    "bool   isTrackerMuon()",
    "double   energy()",
    "double   et()",
    "double   eta()",
    "double   phi()",
    "double   pt()",
    "int   charge()",
    "/",
    "recoSuperCluster                correctedHybridSuperClusters    500",
    #---------------------------------------------------------------------
    "double   energy()",
    "double   eta()",
    "double   etaWidth()",
    "double   phi()",
    "double   phiWidth()",
    "double   preshowerEnergy()",
    "double   rawEnergy()",
    "double   x()",
    "double   y()",
    "double   z()",
    "size_t   clustersSize()",
    "size_t   size()",
    "/",
    "recoSuperCluster     correctedMulti5x5SuperClustersWithPreshower 500",
    #---------------------------------------------------------------------
    "double   energy()",
    "double   eta()",
    "double   etaWidth()",
    "double   phi()",
    "double   phiWidth()",
    "double   preshowerEnergy()",
    "double   rawEnergy()",
    "double   x()",
    "double   y()",
    "double   z()",
    "size_t   clustersSize()",
    "size_t   size()",
    "/",
    "recoSuperCluster                hybridSuperClusters             500",
    #---------------------------------------------------------------------
    "double   energy()",
    "double   eta()",
    "double   etaWidth()",
    "double   phi()",
    "double   phiWidth()",
    "double   preshowerEnergy()",
    "double   rawEnergy()",
    "double   x()",
    "double   y()",
    "double   z()",
    "size_t   clustersSize()",
    "size_t   size()",
    "/",
    "recoSuperCluster                multi5x5SuperClustersWithPreshower 500",
    #---------------------------------------------------------------------
    "double   energy()",
    "double   eta()",
    "double   etaWidth()",
    "double   phi()",
    "double   phiWidth()",
    "double   preshowerEnergy()",
    "double   rawEnergy()",
    "double   x()",
    "double   y()",
    "double   z()",
    "size_t   clustersSize()",
    "size_t   size()",
    "/",
    "recoSuperCluster  multi5x5SuperClusters_multi5x5EndcapSuperClusters 500",
    #---------------------------------------------------------------------
    "double   energy()",
    "double   eta()",
    "double   etaWidth()",
    "double   phi()",
    "double   phiWidth()",
    "double   preshowerEnergy()",
    "double   rawEnergy()",
    "double   x()",
    "double   y()",
    "double   z()",
    "size_t   clustersSize()",
    "size_t   size()",
    "/",
    "recoTrack                       generalTracks                   500",
    #---------------------------------------------------------------------
    "bool   innerOk()",
    "bool   outerOk()",
    "double   chi2()",
    "double   d0()",
    "double   dxy()",
    "double   eta()",
    "double   phi()",
    "double   pt()",
    "int   charge()",
    "/",
    "recoTrack                       globalCosmicMuons               500",
    #---------------------------------------------------------------------
    "bool   innerOk()",
    "bool   outerOk()",
    "double   chi2()",
    "double   d0()",
    "double   dxy()",
    "double   eta()",
    "double   phi()",
    "double   pt()",
    "int   charge()",
    "/",
    "recoTrack                       globalMuons                     500",
    #---------------------------------------------------------------------
    "bool   innerOk()",
    "bool   outerOk()",
    "double   chi2()",
    "double   d0()",
    "double   dxy()",
    "double   eta()",
    "double   phi()",
    "double   pt()",
    "int   charge()",
    "/",
    "recoTrack                       standAloneMuons                 500",
    #---------------------------------------------------------------------
    "bool   innerOk()",
    "bool   outerOk()",
    "double   chi2()",
    "double   d0()",
    "double   dxy()",
    "double   eta()",
    "double   phi()",
    "double   pt()",
    "int   charge()",
    "/",
    "recoVertex                      offlinePrimaryVertices          500",
    #---------------------------------------------------------------------
    "double   chi2()",
    "double   normalizedChi2()",
    "double   x()",
    "double   y()",
    "double   z()",
    "size_t   tracksSize()",
    "/",
    "recoVertex                      pixelVertices                   500",
    #---------------------------------------------------------------------
    "double   chi2()",
    "double   normalizedChi2()",
    "double   x()",
    "double   y()",
    "double   z()",
    "size_t   tracksSize()",
    "/"
    )
               )
