#-------------------------------------------------------------------------
# Created: Thu Jan 21 22:16:44 2010 by mkntuplecfi.py
#-------------------------------------------------------------------------
import FWCore.ParameterSet.Config as cms
demo =\
cms.EDAnalyzer("Mkntuple",
               ntupleName = cms.untracked.string("so10pat_ntuple.root"),
               variables  =
               cms.untracked.
               vstring(
    "recoBeamSpot                    offlineBeamSpot                   1",
    #---------------------------------------------------------------------
    "  double  x0()",
    "  double  y0()",
    "  double  z0()",
    "/",
    "patElectron                     cleanLayer1Electrons            500",
    #---------------------------------------------------------------------
    "     int  charge()",
    "  double  energy()",
    "  double  et()",
    "  double  eta()",
    "  double  phi()",
    "  double  pt()",
    "   float  caloIso()",
    "   float  ecalIso()",
    "   float  hcalIso()",
    "   float  trackIso()",
    "     int  gsfTrack_charge()",
    "  double  gsfTrack_chi2()",
    "  double  gsfTrack_d0()",
    "  size_t  superCluster_clustersSize()",
    "  double  superCluster_energy()",
    "  double  superCluster_eta()",
    "  double  superCluster_etaWidth()",
    "  double  superCluster_phi()",
    "  double  superCluster_phiWidth()",
    "  double  superCluster_preshowerEnergy()",
    "  double  superCluster_rawEnergy()",
    "  size_t  superCluster_size()",
    "  double  superCluster_x()",
    "  double  superCluster_y()",
    "  double  superCluster_z()",
    "/",
    "patJet                          cleanLayer1JetsAK5              500",
    #---------------------------------------------------------------------
    "  double  energy()",
    "   float  energyFractionHadronic()",
    "  double  et()",
    "  double  eta()",
    "  double  p()",
    "  double  phi()",
    "  double  pt()",
    "    bool  isBasicJet()",
    "    bool  isCaloJet()",
    "    bool  isJet()",
    "    bool  isPFJet()",
    #"   float  bDiscriminator(const std::string x)",
    "/",
    "recoGenParticle                 genParticles                   4000",
    #---------------------------------------------------------------------
    "     int  charge()",
    "  double  energy()",
    "  double  et()",
    "  double  eta()",
    "  double  p()",
    "  double  phi()",
    "  double  pt()",
    "  double  px()",
    "  double  py()",
    "  double  pz()",
    "    bool  longLived()",
    "  double  mass()",
    "     int  pdgId()",
    "     int  status()",
    "/",
    "recoTrack                       generalTracks                   500",
    #---------------------------------------------------------------------
    "     int  charge()",
    "  double  eta()",
    "  double  p()",
    "  double  phi()",
    "  double  pt()",
    "  double  chi2()",
    "  double  d0()",
    "  double  normalizedChi2()",
    "/"
    )
               )
