# GNUmakefile to create XML files
# Created: Thu Jan 14 22:45:26 2010 with mkxmlfiles.py $Revision:
#$Revision: 1.12 $
#------------------------------------------------------------------------------
ifndef PYTHON_PROJECTS
$(error PYTHON_PROJECTS is undefined)
endif
#------------------------------------------------------------------------------
h2xmlflags:= -I$(CMSSW_RELEASE_BASE)/src
#------------------------------------------------------------------------------
include $(PYTHON_PROJECTS)/config/xml.mk
