#------------------------------------------------------------------------------
# GNUmakefile
# Build shared library libjetnet.so
# Created: 09-Mar-2004 Harrison B. Prosper
#------------------------------------------------------------------------------
cppflags:= -I../../petra/include
libs	:= -lpetra
#------------------------------------------------------------------------------
include ../../config/library.mk





